# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de385cf97e74d0bd35b2c5154390efda043a35ff9893657b97feb11e1e259564a9b06dd6cf4894b41f803b4d387e3008fbb35e1010020bb6480be76dc0cdcab7

test:
  secret_key_base: ff6d84b33a9046227fd6e5dc4214ed093a202a13fc2412b30ec85f2b48c3023fc693b694bd989e546be8ef07e4c1e5aa02273aa5083b0cd5f4424fa901360e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
